--------------------------------------------------------
--  File created - Sunday-February-06-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table A_ADDRESS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."A_ADDRESS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PERSON_ID" VARCHAR2(20 BYTE), 
	"EFFDT" VARCHAR2(20 BYTE), 
	"COLUMN1" VARCHAR2(20 BYTE), 
	"PERSON_TYPE" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"PINCODE" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"UPDATED_BY" VARCHAR2(20 BYTE), 
	"UPDATED_DATE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.A_ADDRESS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ADDRESS_PK" ON "SYSTEM"."A_ADDRESS" ("ID", "PERSON_ID", "EFFDT", "COLUMN1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table A_ADDRESS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."A_ADDRESS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."A_ADDRESS" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."A_ADDRESS" MODIFY ("EFFDT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."A_ADDRESS" MODIFY ("COLUMN1" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."A_ADDRESS" MODIFY ("PERSON_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."A_ADDRESS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."A_ADDRESS" MODIFY ("PINCODE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."A_ADDRESS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."A_ADDRESS" ADD CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ID", "PERSON_ID", "EFFDT", "COLUMN1")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
