--------------------------------------------------------
--  File created - Sunday-February-06-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table A_INTAKESTAFF
--------------------------------------------------------

  CREATE TABLE "A_INTAKESTAFF" 
   (	"ID" VARCHAR2(20 BYTE), 
	"INTAKE_ID" VARCHAR2(20 BYTE), 
	"STAFF_ID" VARCHAR2(20 BYTE), 
	"EFFDT" VARCHAR2(20 BYTE), 
	"EFFSEQ" VARCHAR2(20 BYTE), 
	"INTAKESTAFF_DATETIME" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"UPDATED_BY" VARCHAR2(20 BYTE), 
	"UPDATED_DATE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into A_INTAKESTAFF
SET DEFINE OFF;
Insert into A_INTAKESTAFF (ID,INTAKE_ID,STAFF_ID,EFFDT,EFFSEQ,INTAKESTAFF_DATETIME,STATUS,UPDATED_BY,UPDATED_DATE) values ('100','100','100','3-05-2020','1','3-05-2020','A',null,null);
Insert into A_INTAKESTAFF (ID,INTAKE_ID,STAFF_ID,EFFDT,EFFSEQ,INTAKESTAFF_DATETIME,STATUS,UPDATED_BY,UPDATED_DATE) values ('101','101','101','2-05-2020','1','2-05-2020','A',null,null);
Insert into A_INTAKESTAFF (ID,INTAKE_ID,STAFF_ID,EFFDT,EFFSEQ,INTAKESTAFF_DATETIME,STATUS,UPDATED_BY,UPDATED_DATE) values ('102','102','102','4-05-2020','1','5-05-2020','A',null,null);
Insert into A_INTAKESTAFF (ID,INTAKE_ID,STAFF_ID,EFFDT,EFFSEQ,INTAKESTAFF_DATETIME,STATUS,UPDATED_BY,UPDATED_DATE) values ('103','103','103','3-07-2020','1','3-07-2020','A',null,null);
Insert into A_INTAKESTAFF (ID,INTAKE_ID,STAFF_ID,EFFDT,EFFSEQ,INTAKESTAFF_DATETIME,STATUS,UPDATED_BY,UPDATED_DATE) values ('104','104','104','9-06-2020','1','9-06-2020','A',null,null);
Insert into A_INTAKESTAFF (ID,INTAKE_ID,STAFF_ID,EFFDT,EFFSEQ,INTAKESTAFF_DATETIME,STATUS,UPDATED_BY,UPDATED_DATE) values ('105','105','105','3-09-2020','1','3-09-2020','A',null,null);
--------------------------------------------------------
--  DDL for Index A_INTAKESTAFF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "A_INTAKESTAFF_PK" ON "A_INTAKESTAFF" ("ID", "INTAKE_ID", "STAFF_ID", "EFFDT", "EFFSEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table A_INTAKESTAFF
--------------------------------------------------------

  ALTER TABLE "A_INTAKESTAFF" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "A_INTAKESTAFF" MODIFY ("INTAKE_ID" NOT NULL ENABLE);
  ALTER TABLE "A_INTAKESTAFF" MODIFY ("STAFF_ID" NOT NULL ENABLE);
  ALTER TABLE "A_INTAKESTAFF" MODIFY ("EFFDT" NOT NULL ENABLE);
  ALTER TABLE "A_INTAKESTAFF" MODIFY ("EFFSEQ" NOT NULL ENABLE);
  ALTER TABLE "A_INTAKESTAFF" MODIFY ("INTAKESTAFF_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "A_INTAKESTAFF" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "A_INTAKESTAFF" ADD CONSTRAINT "A_INTAKESTAFF_PK" PRIMARY KEY ("ID", "INTAKE_ID", "STAFF_ID", "EFFDT", "EFFSEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
