--------------------------------------------------------
--  File created - Sunday-February-06-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table A_PATIENT
--------------------------------------------------------

  CREATE TABLE "A_PATIENT" 
   (	"ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"DOB" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"UPDATED_BY" VARCHAR2(20 BYTE), 
	"UPDATED_DATE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into A_PATIENT
SET DEFINE OFF;
Insert into A_PATIENT (ID,FIRST_NAME,LAST_NAME,DOB,GENDER,UPDATED_BY,UPDATED_DATE) values (100,'lalitha','reddy','02-05-1999','f',null,null);
Insert into A_PATIENT (ID,FIRST_NAME,LAST_NAME,DOB,GENDER,UPDATED_BY,UPDATED_DATE) values (101,'lohita','reddy','02-05-1998','f',null,null);
Insert into A_PATIENT (ID,FIRST_NAME,LAST_NAME,DOB,GENDER,UPDATED_BY,UPDATED_DATE) values (102,'lokesh','reddy','02-05-1989','m',null,null);
Insert into A_PATIENT (ID,FIRST_NAME,LAST_NAME,DOB,GENDER,UPDATED_BY,UPDATED_DATE) values (103,'sneha','reddy','04-05-1999','f',null,null);
Insert into A_PATIENT (ID,FIRST_NAME,LAST_NAME,DOB,GENDER,UPDATED_BY,UPDATED_DATE) values (104,'ramesh','kumar','02-03-1999','f',null,null);
Insert into A_PATIENT (ID,FIRST_NAME,LAST_NAME,DOB,GENDER,UPDATED_BY,UPDATED_DATE) values (105,'preethi','singh','05-03-1988','f',null,null);
--------------------------------------------------------
--  DDL for Index PATIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PATIENT_PK" ON "A_PATIENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table A_PATIENT
--------------------------------------------------------

  ALTER TABLE "A_PATIENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "A_PATIENT" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "A_PATIENT" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "A_PATIENT" MODIFY ("DOB" NOT NULL ENABLE);
  ALTER TABLE "A_PATIENT" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "A_PATIENT" ADD CONSTRAINT "PATIENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
